version: '3.9'

services:
  rest-api-server:
    image: rest-api-server
    container_name: rest-api-server
    networks:
      - rest-api-network
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        APP_PORT: ${APP_PORT}
    env_file: ./.env
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: unless-stopped

  rest-api-redis:
    image: redis:7
    container_name: rest-api-redis
    networks:
      - rest-api-network
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./.cloud/redis.conf:/usr/local/etc/redis/redis.conf
      - rest-api-redis-data:/data
    ports:
      - ${REDIS_PORT}:6379
    restart: unless-stopped

  rest-api-db:
    image: postgres:15
    container_name: rest-api-db
    networks:
      - rest-api-network
    volumes:
      - rest-api-db-data:/var/lib/postgresql/data
    environment:
      TZ: 'UTC'
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped

volumes:
  rest-api-redis-data:
    driver: local
  rest-api-db-data:
    driver: local

networks:
  rest-api-network:
    name: rest-api-network
