name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'http/**'
      - '*.md'
      - 'templates/**'

  pull_request:
    branches:
        - develop
        - main
    paths-ignore:
      - 'docs/**'
      - 'http/**'
      - '*.md'
      - 'templates/**'
    types: [opened, synchronize, closed]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  # dependency-review:
  #   name: Dependency Review
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read

  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@v4
  #       with:
  #         persist-credentials: false

  #     - name: Dependency review
  #       uses: actions/dependency-review-action@v3

  build-test:
    if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))

    name: Build & ESLint & Unit test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: ESLint Check
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit:ci

      - name: Build
        run: npm run build

      - name: Upload test results
        uses: actions/upload-artifact@v4  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-result-${{ matrix.node-version }}
          path: reports/jest-*.xml
